#<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Advocating for the Masalit people through culture, history, and support initiatives.">
  <title>Masalit Culture Advocates</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f4f4f9;
      color: #333;
    }
    header {
      background-color: #003366;
      color: #fff;
      padding: 20px;
      text-align: center;
    }
    nav {
      background-color: #005599;
      padding: 10px;
      text-align: center;
    }
    nav a {
      color: #fff;
      text-decoration: none;
      margin: 0 15px;
      font-weight: bold;
    }
    section {
      padding: 20px;
      max-width: 1000px;
      margin: auto;
    }
    h2 {
      color: #003366;
    }
    iframe {
      width: 100%;
      height: 315px;
      margin: 20px 0;
    }
    footer {
      background-color: #003366;
      color: #fff;
      text-align: center;
      padding: 15px;
      margin-top: 40px;
    }
  </style>
</head>
<body>
  <header>
    <h1>Masalit Culture Advocates</h1>
    <p>Preserving history. Empowering the future.</p>
  </header>
  <nav>
    <a href="#history">History</a>
    <a href="#culture">Culture</a>
    <a href="#support">Support</a>
    <a href="#music">Music</a>
    <a href="#contact">Contact</a>
  </nav>

  <section id="history">
    <h2>Who Are the Masalit?</h2>
    <p>The <strong>Masalit</strong> are an ethnic group primarily found in <strong>western Sudan</strong> and parts of <strong>eastern Chad</strong>... [Full content continues as per your submission]</p>
  </section>

  <section id="support">
    <h2>Supporting the Masalit People</h2>
    <ol>
      <li><strong>Peace and Protection:</strong> Advocate for peace, justice, and protection of civilians.</li>
      <li><strong>Humanitarian Aid and Reconstruction:</strong> Support displaced communities and rebuild infrastructure.</li>
      <li><strong>Education and Economic Empowerment:</strong> Invest in schools and sustainable livelihoods.</li>
      <li><strong>Cultural Preservation:</strong> Promote Masalit language, arts, and traditions.</li>
      <li><strong>Digital Inclusion:</strong> Improve internet access and storytelling platforms.</li>
    </ol>
  </section>

  <section id="music">
    <h2>Masalit Songs</h2>
    <iframe src="https://www.youtube.com/embed/videoseries?list=PL3RiibhGD7593YNzWpKUdBA" frameborder="0" allowfullscreen></iframe>
  </section>

  <section id="contact">
    <h2>Contact</h2>
    <p>Email: <a href="mailto:Ragelin31@gmail.com">Ragelin31@gmail.com</a></p>
  </section>

  <footer>
    <p>&copy; 2025 Masalit Culture Advocates. All rights reserved.</p>
  </footer>
</body>
</html>
 This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
